version: "3"
services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: reading-point/auth_service:v1.0
    container_name: reading-point-auth-app-service
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    tty: true
    environment:
      SERVICE_NAME: auth_service
      SERVICE_TAGS: v1
      APP_NAME: auth_service
      APP_ENV: local
      APP_KEY: 28ef3d143ba729acf55d43f3a0f12c65
      APP_DEBUG: 0
      APP_URL: http://auth_service
      APP_TIMEZONE: UTC

      LOG_CHANNEL: stack
      LOG_SLACK_WEBHOOK_URL:

      DB_CONNECTION: mysql
      DB_HOST: reading_point_db
      DB_PORT: 3306
      DB_DATABASE: reading_point_auth
      DB_USERNAME: root
      DB_PASSWORD: unpri2022

      CACHE_DRIVER: redis
      QUEUE_CONNECTION: sync
      REDIS_HOST: reading-point-auth-redis-service
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      REDIS_PASSWORD: halotec123
      JWT_SECRET: jrB6NFAISKe4jJ03Cakkl9cn7y8RxRQagF5d2rEGdpRs7CqJSRyZt2CG3gzEYDt1
      JWT_ALGO: HS256

    working_dir: /var/www/html

    command: php -S auth_service:8000 -t public
    ports:
      - "8901:8000"
    networks:
      - reading-point-auth-network

  reading_point_db:
    image: mariadb:10.6
    container_name: reading-point-auth-db-service
    volumes:
      - reading-point-auth-service-db:/var/lib/mysql
    restart: unless-stopped
    tty: true

    environment:
      MYSQL_DATABASE: reading_point_auth
      MYSQL_ROOT_PASSWORD: unpri2022

    networks:
      - reading-point-auth-network
  redis_service:
    image: redis:7.0.5-alpine
    container_name: reading-point-auth-redis-service
    environment:
      - REDIS_PORT_NUMBER=6379

    command: redis-server --save 20 1 --loglevel warning --requirepass halotec123
    volumes:
      - cache:/data
    networks:
      - reading-point-auth-network
networks:
  reading-point-auth-network:
    driver: bridge
    name: reading-point-auth-network
volumes:
  reading-point-auth-service-db:
    driver: local
    name: reading-point-auth-service-db-vol
  cache:
    driver: local
    name: reading-point-auth-redis_cache
